### ISSUE TITLE
Javascript error in Copy of Clipboard from Contract Box

### ISSUE THREAD

**Issue by cointastical** [Reckless-Satoshi/robosats#65] opened 2022-03-06 15:29 UTC
In trying to pay the committment trx to PUBLISH my order, when I see the Contract Box, with the QR code, I then tried to press Copy To Clipboard

Expected behavior:
That the LN Invoice would be copied to my clipboard

Actual behavior: 
No change to my clipboard.

In showing the Javascript console, I see: 

    react-dom.production.min.js:101 Uncaught TypeError: Cannot read properties of undefined 
    (reading 'writeText')
        at onClick (TradeBox.js:213:31)
        at Object.Rb (react-dom.production.min.js:52:317)
        at Xb (react-dom.production.min.js:52:471)
        at Yb (react-dom.production.min.js:53:35)
        at Ze (react-dom.production.min.js:100:68)
        at se (react-dom.production.min.js:101:380)
        at eval (react-dom.production.min.js:113:65)
        at Jb (react-dom.production.min.js:292:189)
        at Nb (react-dom.production.min.js:50:57)
        at jd (react-dom.production.min.js:105:469)

**Comment by cointastical** [comment] 2022-03-06 15:31
This is occurring using Brave Browser 
[Version 1.36.109 Chromium: 99.0.4844.51 (Official Build) (64-bit)](https://brave.com/latest/)

**Comment by Reckless-Satoshi** [comment] 2022-03-06 17:00
Hey @cointastical ,

Thanks for opening this issue. 

The clipboard not working issue only happens in Brave's "Private window with Tor". Seems like some functions are disabled in Brave with Tor, probably this is a Brave privacy protecting feature and there does not seem to be many ways around it. I have not found any related discussion online about this issue with Brave.

Any other torified browser or Brave when not used with Tor (this can only be tested when using the development platform) works just fine. Meaning, the issue is probably Brave. Tor Browser is strongly recommended to use with RoboSats.

**Comment by Reckless-Satoshi** [comment] 2022-06-27 22:17
Confirmed as a Tor Browser w/ Tor issue. It just won't copy with the button. Closing.

**Closed by Reckless-Satoshi** 2022-06-27 22:17 UTC
Labels: needs research
