### ISSUE TITLE
[solved] QtQr adds invisible characters front of the string in the QRcode

### ISSUE THREAD

**Issue by openoms** [Reckless-Satoshi/robosats#214] opened 2022-08-21 17:46 UTC
Shared the robot code to mobile and different avatar came up without the ongoing trade.

Tor Browser on Android: 99.0.0b3 (11.5)

Latest Tor Browser on desktop + Brave was consistent with the original account.

Previously could recover the same account on mobile.

**Comment by Reckless-Satoshi** [comment] 2022-08-21 18:55
> Shared the robot code to mobile and different avatar came up without the ongoing trade.

Do you know what are the steps I should take to replicate this bug? In order to better identify this bug and fix it, it would be great if we can find a token (not the one you are using) for which this behavior is true (i.e., generates a different robot in desktop and mobile).

I assume you did good diligence before reporting, but are you sure the token did not corrupt while transferring devices? When manually entering a token, it is important to note that base64 has both `I` and `l` and `0` and `O`. These might look identical with some fonts. I have recovered a robot from device to device many times. Sometimes, I recovered a different robot, but always found out it was my mistake when typing.

The frontend token hashing function is the same for both desktop and mobile (in fact, the whole frontend is the same). The hash of the token is the robot identity, so same hash -> same avatar. It would be surprising, at this stage, if this setup is not reliable.

**Comment by openoms** [comment] 2022-08-21 19:15
steps taken:
* start trade on desktop, save token as offered (copy-paste)
* share token via Linux QtQR and Binary Eye on Android - confirmed the same visually. 
* on Android the avatar and name is different reproducible with this code.
* the original account is recoverable on desktop.
Due to the nature of the trade will be able to share the robot token privately after finished.

**Comment by Reckless-Satoshi** [comment] 2022-08-21 19:40
I was able to replicate your issue, I am puzzled. These are my findings: Linux QtQR generates a QR whose token is different. 

Using the following QR encoding software solved the issue for me:
```bash
apt install qrencode
qrencode -o token.png
```
QR code generated by QtQR:
![qtqr](https://user-images.githubusercontent.com/90936742/185807946-23da2abf-337d-49e5-b29a-32d7fbff9484.png)

QR code generated by `qrencode`:
![token](https://user-images.githubusercontent.com/90936742/185807910-b1b57730-f9b1-4e52-a20d-015a73b807ad.png)

These two token strings seem identical. Yet, they are different. The frontend recognizes they are different when you replace one by the other (the "generate Robot" button turns blue, that does not happen if you replace text by itself by copy/pasting).

I need a little bit of time to find out what is actually different between these two strings.

**Comment by Reckless-Satoshi** [comment] 2022-08-21 21:47
Assuming the issue is exclusive to QtQR, maybe the best solution is to simply avoid this tool and document it. This problem might also occur and be very annoying if you use it to copy a password or a BTC address to your device.

I tested whether this hypothesis is true by sending a txid from mempool.space to the Android device:
1. Find a txid hex in mempool.space
2. Generate a QR code with QtQR and scan with SecScanQR on Android
3. Navigate to mempool.space/tx/<past_txid> in the Android device

The result is _"Invalid hex string"_ . 

One can also see on the browser bar that the URL has characters `%EF%BB%BF` ( the _[Byte order mark](https://simple.wikipedia.org/wiki/Byte_order_mark)_ for UTF-8 also `ï»¿`). I wonder whether it is typical practice to include this mark on QR codes or copy these bytes into the clipboard :thinking: 

As a solution for future users encountering a similar problem, the frontend could check for `%EF%BB%BF` at the start of the token sequence. Yet, one would think browsers are already this smart.

**Comment by openoms** [comment] 2022-08-21 22:07
This is scary as I was using QtQr occasionally for various things including sharing invoices and PSBTs. Well won't do it any more. Likely other projects would benefit from a warning as well.

Regarding the example QRs above Binary Eye does display the problem in the hex representation and showing empty characters et the beginning of the token:

![5cc3cc37-27d7-40f3-826a-a2ba2caaab17](https://user-images.githubusercontent.com/43343391/185812835-46af4e8d-2c9d-42b4-a05a-b0f73f8843e3.png)
vs the second picture:
![486b2128-240a-491f-b9fa-7c1d1706699f](https://user-images.githubusercontent.com/43343391/185812847-a5223cf2-8254-4833-ac75-95fd13ad91cf.png)

**Comment by openoms** [comment] 2022-08-21 22:15
Clearly not a problem with Robosats, renaming and happy to close.

**Closed** 2022-08-21 23:34 UTC
Labels: needs research
